version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.11
 build: 
  commands:
   - sam build
   - export BUCKET=zambark-crs-pipeline-output
   - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
 type: zip
 files:
  - template.yml
  - outputtemplate.yml